
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include "../ft_printf/include/ft_printf.h"
#include <limits.h>

int main(int argc, char *argv[])
{
	int fd;
	int expected_return_value = 0;
	int actual_return_value = 0;

	char *input = "ft_printf_inputs.txt";
	char *expected = "expected.txt";
	close(1);
	fd = open(input, O_WRONLY | O_CREAT, 0644);
	if (fd == -1)
	{
        	perror("open failed");
        	exit(1);
    	}
    	actual_return_value += ft_printf("\n----------------------------------------\n");
    	actual_return_value += ft_printf("%%c:\n");
    	actual_return_value += ft_printf("%c", '0');
    	actual_return_value += ft_printf(" %c ", '0');
    	actual_return_value += ft_printf(" %c", '0' - 256);
    	actual_return_value += ft_printf("%c ", '0' + 256);
    	actual_return_value += ft_printf(" %c %c %c ", '0', 0, '1');
    	actual_return_value += ft_printf(" %c %c %c ", ' ', ' ', ' ');
    	actual_return_value += ft_printf(" %c %c %c ", '1', '2', '3');
    	actual_return_value += ft_printf(" %c %c %c ", 0, '2', '3');
    	actual_return_value += ft_printf(" %c %c %c ", '1', '2', 0);
    	actual_return_value += ft_printf("\n----------------------------------------\n");
    	actual_return_value += ft_printf("%%d:\n");
    	actual_return_value += ft_printf("%d", 0);
    	actual_return_value += ft_printf("%d", -123);
    	actual_return_value += ft_printf("%d",INT_MAX);
    	actual_return_value += ft_printf("%d",INT_MIN);
    	actual_return_value += ft_printf("%d",UINT_MAX);
    	actual_return_value += ft_printf("%d",LONG_MAX);
    	actual_return_value += ft_printf("%d",LONG_MIN);
    	actual_return_value += ft_printf("%d",UINT_MAX);
    	actual_return_value += ft_printf("%d",ULONG_MAX);
    	actual_return_value += ft_printf("%d", 9223372036854775807LL);
    	actual_return_value += ft_printf("\n----------------------------------------\n");
    	actual_return_value += ft_printf("%%%%:\n");
    	actual_return_value += ft_printf("%%");
    	actual_return_value += ft_printf(" %%%% ");
    	actual_return_value += ft_printf("%% %% %% %% ");
    	actual_return_value += ft_printf(" %% %% %%");
    	actual_return_value += ft_printf("\n----------------------------------------\n");
    	actual_return_value += ft_printf("%%s:\n");
    	actual_return_value += ft_printf("%s", "");
    	actual_return_value += ft_printf("%s", " ");
    	actual_return_value += ft_printf("%s", NULL);
    	actual_return_value += ft_printf("%s %s", NULL, "11");
    	actual_return_value += ft_printf("%s %s %s %s", "", " - ", "" , NULL);
    	actual_return_value += ft_printf("%s %s %s %s", "3", " NULL ", "4" , "s");
    	actual_return_value += ft_printf("\n----------------------------------------\n");
    	actual_return_value += ft_printf("%%i:\n");
    	actual_return_value += ft_printf("%i", 0);
    	actual_return_value += ft_printf("%i", -123);
    	actual_return_value += ft_printf("%i",INT_MAX);
    	actual_return_value += ft_printf("%i",INT_MIN);
    	actual_return_value += ft_printf("%i",UINT_MAX);
    	actual_return_value += ft_printf("%i",LONG_MAX);
    	actual_return_value += ft_printf("%i",LONG_MIN);
    	actual_return_value += ft_printf("%i",UINT_MAX);
    	actual_return_value += ft_printf("%i",ULONG_MAX);
    	actual_return_value += ft_printf("%i", 9223372036854775807LL);
    	actual_return_value += ft_printf("\n----------------------------------------\n");
    	actual_return_value += ft_printf("%%u:\n");
    	actual_return_value += ft_printf("%u", 0);
    	actual_return_value += ft_printf("%u", -123);
    	actual_return_value += ft_printf("%u",INT_MAX);
    	actual_return_value += ft_printf("%u",INT_MIN);
    	actual_return_value += ft_printf("%u",UINT_MAX);
    	actual_return_value += ft_printf("%u",LONG_MAX);
    	actual_return_value += ft_printf("%u",LONG_MIN);
    	actual_return_value += ft_printf("%u",UINT_MAX);
    	actual_return_value += ft_printf("%u",ULONG_MAX);
    	actual_return_value += ft_printf("%u", 9223372036854775807LL);
    	actual_return_value += ft_printf("\n----------------------------------------\n");
    	actual_return_value += ft_printf("%%p:\n");
	actual_return_value += ft_printf("%p", -1);
	actual_return_value += ft_printf("%p", 1);
	actual_return_value += ft_printf("%p", 15);
	actual_return_value += ft_printf("%p", 16);
	actual_return_value += ft_printf("%p %p", LONG_MIN, LONG_MAX);
	actual_return_value += ft_printf("%p %p", ULONG_MAX, -ULONG_MAX);
	actual_return_value += ft_printf("%p %p", 0, 0);
    	actual_return_value += ft_printf("\n----------------------------------------\n");
    	actual_return_value += ft_printf("%%x:\n");
	actual_return_value += ft_printf("%x", -1);
	actual_return_value += ft_printf("%x", 1);
	actual_return_value += ft_printf("%x", 15);
	actual_return_value += ft_printf("%x", 16);
	actual_return_value += ft_printf("%x %x", LONG_MIN, LONG_MAX);
	actual_return_value += ft_printf("%x %x", ULONG_MAX, -ULONG_MAX);
	actual_return_value += ft_printf("%x %x", 0, 0);
    	actual_return_value += ft_printf("\n----------------------------------------\n");
    	actual_return_value += ft_printf("%%X:\n");
	actual_return_value += ft_printf("%X", -1);
	actual_return_value += ft_printf("%X", 1);
	actual_return_value += ft_printf("%X", 15);
	actual_return_value += ft_printf("%X", 16);
	actual_return_value += ft_printf("%X %X", LONG_MIN, LONG_MAX);
	actual_return_value += ft_printf("%X %X", ULONG_MAX, -ULONG_MAX);
	actual_return_value += ft_printf("%X %X", 0, 0);
	ft_printf("\n%d", actual_return_value);
	
	close(1);
	fd = open(expected, O_WRONLY | O_CREAT, 0644);
	if (fd == -1)
	{
        	perror("open failed");
        	exit(1);
    	}
    	expected_return_value += printf("\n----------------------------------------\n");
    	expected_return_value += printf("%%c:\n");
    	expected_return_value += printf("%c", '0');
    	expected_return_value += printf(" %c ", '0');
    	expected_return_value += printf(" %c", '0' - 256);
    	expected_return_value += printf("%c ", '0' + 256);
    	expected_return_value += printf(" %c %c %c ", '0', 0, '1');
    	expected_return_value += printf(" %c %c %c ", ' ', ' ', ' ');
    	expected_return_value += printf(" %c %c %c ", '1', '2', '3');
    	expected_return_value += printf(" %c %c %c ", 0, '2', '3');
    	expected_return_value += printf(" %c %c %c ", '1', '2', 0);
    	expected_return_value += printf("\n----------------------------------------\n");
    	expected_return_value += printf("%%d:\n");
    	expected_return_value += printf("%d", 0);
    	expected_return_value += printf("%d", -123);
    	expected_return_value += printf("%d",INT_MAX);
    	expected_return_value += printf("%d",INT_MIN);
    	expected_return_value += printf("%d",UINT_MAX);
    	expected_return_value += printf("%d",LONG_MAX);
    	expected_return_value += printf("%d",LONG_MIN);
    	expected_return_value += printf("%d",UINT_MAX);
    	expected_return_value += printf("%d",ULONG_MAX);
    	expected_return_value += printf("%d", 9223372036854775807LL);
    	expected_return_value += printf("\n----------------------------------------\n");
    	expected_return_value += printf("%%%%:\n");
    	expected_return_value += printf("%%");
    	expected_return_value += printf(" %%%% ");
    	expected_return_value += printf("%% %% %% %% ");
    	expected_return_value += printf(" %% %% %%");
    	expected_return_value += printf("\n----------------------------------------\n");
    	expected_return_value += printf("%%s:\n");
    	expected_return_value += printf("%s", "");
    	expected_return_value += printf("%s", " ");
    	expected_return_value += printf("%s", NULL);
    	expected_return_value += printf("%s %s", NULL, "11");
    	expected_return_value += printf("%s %s %s %s", "", " - ", "" , NULL);
    	expected_return_value += printf("%s %s %s %s", "3", " NULL ", "4" , "s");
    	expected_return_value += printf("\n----------------------------------------\n");
    	expected_return_value += printf("%%i:\n");
    	expected_return_value += printf("%i", 0);
    	expected_return_value += printf("%i", -123);
    	expected_return_value += printf("%i",INT_MAX);
    	expected_return_value += printf("%i",INT_MIN);
    	expected_return_value += printf("%i",UINT_MAX);
    	expected_return_value += printf("%i",LONG_MAX);
    	expected_return_value += printf("%i",LONG_MIN);
    	expected_return_value += printf("%i",UINT_MAX);
    	expected_return_value += printf("%i",ULONG_MAX);
    	expected_return_value += printf("%i", 9223372036854775807LL);
    	expected_return_value += printf("\n----------------------------------------\n");
    	expected_return_value += printf("%%u:\n");
    	expected_return_value += printf("%u", 0);
    	expected_return_value += printf("%u", -123);
    	expected_return_value += printf("%u",INT_MAX);
    	expected_return_value += printf("%u",INT_MIN);
    	expected_return_value += printf("%u",UINT_MAX);
    	expected_return_value += printf("%u",LONG_MAX);
    	expected_return_value += printf("%u",LONG_MIN);
    	expected_return_value += printf("%u",UINT_MAX);
    	expected_return_value += printf("%u",ULONG_MAX);
    	expected_return_value += printf("%u", 9223372036854775807LL);
    	expected_return_value += printf("\n----------------------------------------\n");
    	expected_return_value += printf("%%p:\n");
	expected_return_value += printf("%p", -1);
	expected_return_value += printf("%p", 1);
	expected_return_value += printf("%p", 15);
	expected_return_value += printf("%p", 16);
	expected_return_value += printf("%p %p", LONG_MIN, LONG_MAX);
	expected_return_value += printf("%p %p", ULONG_MAX, -ULONG_MAX);
	expected_return_value += printf("%p %p", 0, 0);
    	expected_return_value += printf("\n----------------------------------------\n");
    	expected_return_value += printf("%%x:\n");
	expected_return_value += printf("%x", -1);
	expected_return_value += printf("%x", 1);
	expected_return_value += printf("%x", 15);
	expected_return_value += printf("%x", 16);
	expected_return_value += printf("%x %x", LONG_MIN, LONG_MAX);
	expected_return_value += printf("%x %x", ULONG_MAX, -ULONG_MAX);
	expected_return_value += printf("%x %x", 0, 0);
    	expected_return_value += printf("\n----------------------------------------\n");
    	expected_return_value += printf("%%X:\n");
	expected_return_value += printf("%X", -1);
	expected_return_value += printf("%X", 1);
	expected_return_value += printf("%X", 15);
	expected_return_value += printf("%X", 16);
	expected_return_value += printf("%X %X", LONG_MIN, LONG_MAX);
	expected_return_value += printf("%X %X", ULONG_MAX, -ULONG_MAX);
	expected_return_value += printf("%X %X", 0, 0);
	printf("\n%d", expected_return_value);
    	exit(0);
}
